title: Mitt CV Repository
Description: Denne nettsiden inneholder en generert utgave av min CV, i engelsk og i norsk versjon.
name: CV Harry Solsem
# remote_theme: pages-themes/hacker@v0.2.0
remote_theme: pages-themes/merlot@v0.2.0
encoding: UTF-8
show_downloads: false