title: My CV Repository 
Description: Denne nettsiden inneholder en generert utgave av min CV, i engelsk og norsk versjon
name: CV Harry Solsem
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
encoding: UTF-8
show_downloads: false